### ISSUE TITLE
Gerbers

### ISSUE THREAD

**Issue by dwhacks** [sensepost/USaBUSe#1]
I was thinking of trying to build a board but there is no board outline file in the gerbers folder, at least not one oshpark recognized.

**Comment by singe** [comment]
We'll get on that.

**Comment by RoganDawes** [comment]
Hi @dwhacks,

Our designer has informed us that the board outline provided was actually for two boards on a single PCB. He will provide an outline of a single board shortly, I hope to have it up by Monday.

**Comment by RoganDawes** [comment]
Updated Gerbers have been added to the repository.

**Comment by dwhacks** [comment]
I have tried adding the Gerbers to Oshpark. First it seems the outline is still for two boards, and after this it is for one board plus a blank section that should be between the two board version. 

I would love to build one of these, so maybe you could get a working board on Oshpark for people like me who just want One or Two could order. 

Thanks!
