### ISSUE TITLE
sdcard reader

### ISSUE THREAD

**Issue by raoul170** [sensepost/USaBUSe#12]
produced some boards, but cannot find correct SDcard reader connector, any help/link appriciated

**Comment by singe** [comment]
Can you provide some more detail?

**Comment by raoul170** [comment]
need a partnumber for the SD card connector on the board.

**Comment by RoganDawes** [comment]
We have requested the full BoM from the designer/fabricator, and I'll add it to the repo once I receive it.

**Comment by RoganDawes** [comment]
The BoM has been added to the /hardware directory.
