### ISSUE TITLE
Setup USaBUSe on whid cactus

### ISSUE THREAD

**Issue by k0stQs** [sensepost/USaBUSe#19]
Are there instructions for installing/setup USaBUSe on the whid cactus?

**Comment by RoganDawes** [comment]
Hi,

Not currently, but it is not too complicated. The main thing is to use the correct tag when checking out.

After cloning the repository, you should checkout the ```whid``` tag:
```
git clone --recursive https://github.com/SensePost/USaBUSe
git checkout whid
```

Then follow the steps in README.md.
