### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by raoul170** [sensepost/USaBUSe#2]
There is currently no BOM in hardware section

**Comment by singe** [comment]
We'll get on that.

**Comment by RoganDawes** [comment]
Hi Raoul,

Our designer will provide us with a formal BOM today, or over the weekend, he said, but did also mention that the necessary components are mentioned in the schematic as well.

If that is not enough for you, the BOM should be up by Monday, hopefully.

**Comment by RoganDawes** [comment]
BOM added
