### ISSUE TITLE
same design like USaBUSe

### ISSUE THREAD

**Issue by h4kb4n** [sensepost/USaBUSe#9]
https://github.com/RadioWar/FireGoose 
we open source now

**Comment by LucaBongiorni** [comment]
English is usually much more appreciated than Chinese language ;)

**Comment by h4kb4n** [comment]
no problem we can translate to english

**Comment by LucaBongiorni** [comment]
That's cool! Thanks!
P.S. I have seen that Firegoose is on sale on Taobao. Maybe it could be put on Aliexpress/Ebay?
Because Taobao is quite closed for non-chinese buyers. And using a broker is not very comfortable. ;]

**Comment by h4kb4n** [comment]
Sorry man, already sold out

**Comment by LucaBongiorni** [comment]
Too bad! Keep me in consideration for the next batch then ;]

**Comment by RoganDawes** [comment]
Hi,

This looks interesting - it's definitely a good idea to have a more powerful processor dealing with the USB side of things, for best performance! I looked at the BOM on your github site, but was not able to see which wireless module you are using?

**Comment by h4kb4n** [comment]
i can give you wifi module info

**Comment by RoganDawes** [comment]
Thank you. I look forward to seeing what you are using.

**Comment by h4kb4n** [comment]
FSEUMH1D1-08G
WM7601WU-YM(Wireless Module)

we dont want to update any more ,so if you want to keep going ,  we will very happy ! thx

**Comment by RoganDawes** [comment]
I do intend to develop this further, mainly to improve performance, but also to add new functions.

**Comment by h4kb4n** [comment]
great,if you want to help or anything tell me~ i will support it
